all:
  hosts:
  children:
    tf2:
      hosts:
        lax.us.uncletopia.com:
          ansible_python_interpreter: python3
        sfo.us.uncletopia.com:
          ansible_python_interpreter: python3
        sea.us.uncletopia.com:
          ansible_python_interpreter: python3
        chi.us.uncletopia.com:
          ansible_python_interpreter: python3
        dal.us.uncletopia.com:
          ansible_python_interpreter: python3
        nyc.us.uncletopia.com:
          ansible_python_interpreter: python3
        atl.us.uncletopia.com:
          ansible_python_interpreter: python3
        fra.de.uncletopia.com:
          ansible_python_interpreter: python3
        ber.de.uncletopia.com:
          ansible_python_interpreter: python3
        ham.de.uncletopia.com:
          ansible_python_interpreter: python3
