all:
  hosts:
  children:
    tf2:
      hosts:
        us[1:4].uncledane.com:
          ansible_python_interpreter: python3
        eu[1:2].uncledane.com:
          ansible_python_interpreter: python3