all:
  hosts:
  children:
    tf2:
      hosts:
        us-west[1:3].uncletopia.com:
          ansible_python_interpreter: python3
        us-central[1:2].uncletopia.com:
          ansible_python_interpreter: python3
        us-east[1:1].uncletopia.com:
          ansible_python_interpreter: python3
        us-south[1:1].uncletopia.com:
          ansible_python_interpreter: python3
        eu-[1:3].uncletopia.com:
          ansible_python_interpreter: python3
