all:
  hosts:
  children:
    tf2:
      hosts:
        lax-1.us.uncletopia.com:
          ansible_python_interpreter: python3
        sfo-1.us.uncletopia.com:
          ansible_python_interpreter: python3
        sea-1.us.uncletopia.com:
          ansible_python_interpreter: python3
        chi-1.us.uncletopia.com:
          ansible_python_interpreter: python3
        dal-1.us.uncletopia.com:
          ansible_python_interpreter: python3
        nyc-1.us.uncletopia.com:
          ansible_python_interpreter: python3
        atl-1.us.uncletopia.com:
          ansible_python_interpreter: python3
        fra-1.de.uncletopia.com:
          ansible_python_interpreter: python3
        ber-1.de.uncletopia.com:
          ansible_python_interpreter: python3
        ham-1.de.uncletopia.com:
          ansible_python_interpreter: python3
