all:
  hosts:
  children:
    tf2:
      hosts:
        lax-[1:1].us.uncletopia.com:
          ansible_python_interpreter: python3
        sfo-[1:1].us.uncletopia.com:
          ansible_python_interpreter: python3
        sea-[1:1].us.uncletopia.com:
          ansible_python_interpreter: python3
        chi-[1:1].us.uncletopia.com:
          ansible_python_interpreter: python3
        dal-[1:1].us.uncletopia.com:
          ansible_python_interpreter: python3
        nyc-[1:1].us.uncletopia.com:
          ansible_python_interpreter: python3
        atl-[1:1].us.uncletopia.com:
          ansible_python_interpreter: python3
        fra-[1:3].de.uncletopia.com:
          ansible_python_interpreter: python3
