---
- name: Clean ~/build_sourcemod/ directory
  ansible.builtin.file:
    path: ~/build_sourcemod/
    state: absent
    mode: "0775"
  tags: clean

- name: Create ~/build_sourcemod/ directory
  ansible.builtin.file:
    path: ~/build_sourcemod/
    state: directory
    mode: "0775"

- name: Download latest metamod
  ansible.builtin.unarchive:
    src: https://mms.alliedmods.net/mmsdrop/1.12/mmsource-1.12.0-git1189-linux.tar.gz
    dest: ~/build_sourcemod/
    remote_src: true
    creates: ~/build_sourcemod/addons/metamod

- name: Download latest sourcemod
  ansible.builtin.unarchive:
    src: "{{ sm_download|default(\"https://sm.alliedmods.net/smdrop/1.12/sourcemod-1.12.0-git7086-linux.tar.gz\") }}"
    dest: ~/build_sourcemod/
    remote_src: true
    creates: ~/build_sourcemod/addons/sourcemod

- name: Copy extensions & plugin sources
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/"
    dest: ~/build_sourcemod/

#
#- name: Copy extensions & plugin sources
#  ansible.builtin.copy:
#    src: "{{ role_path }}/files/"
#    dest: ~/build_sourcemod/
#  vars:
#    debugmode: true

- name: Build plugins
  ansible.builtin.command:
    chdir: ~/build_sourcemod/addons/sourcemod/scripting
    cmd: bash build.sh
