---
- name: Create ~/build_sourcemod/ directory
  ansible.builtin.file:
    path: ~/build_sourcemod/
    state: absent
    mode: "0775"

- name: Create ~/build_sourcemod/ directory
  ansible.builtin.file:
    path: ~/build_sourcemod/
    state: directory
    mode: "0775"

- name: Download latest metamod
  ansible.builtin.unarchive:
    src: https://mms.alliedmods.net/mmsdrop/1.11/mmsource-1.11.0-git1148-linux.tar.gz
    dest: ~/build_sourcemod/
    remote_src: true

- name: Download latest sourcemod
  ansible.builtin.unarchive:
    src: https://sm.alliedmods.net/smdrop/1.12/sourcemod-1.12.0-git7038-linux.tar.gz
    dest: ~/build_sourcemod/
    remote_src: true

- name: Copy extensions & plugin sources
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: ~/build_sourcemod/

- name: Build plugins
  ansible.builtin.command:
    chdir: ~/build_sourcemod/addons/sourcemod/scripting
    cmd: bash build.sh
