---
- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ timezone }}"

- name: Check if i386 is enabled
  ansible.builtin.shell: |
    set -o pipefail
    dpkg --print-foreign-architectures | grep i386
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Enable i386 architecture
  become: true
  ansible.builtin.command: dpkg --add-architecture i386
  when: result_i386_check.rc == 1

- name: Install gpg
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
    state: present
    pkg:
      - gpg

- name: Download docker gpg key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add specified repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install OS Dependencies
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
    state: present
    pkg:
      - wget
      - unzip
      - apt-transport-https
      - ca-certificates
      - gpg
      - curl
      - gnupg
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-docker
      - python3-distutils
      - libc6:i386
      - lib32stdc++6

- name: Add docker group to user
  become: true
  ansible.builtin.user:
    name: tf2server
    groups: docker
    append: true
    state: present

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Increase default available memory for UDP send buffers
  become: true
  ansible.posix.sysctl:
    name: net.core.wmem_default
    value: "52428800"
    sysctl_set: true
    reload: true

- name: Increase available memory for UDP send buffers
  become: true
  ansible.posix.sysctl:
    name: net.core.wmem_max
    value: "52428800"
    sysctl_set: true
    reload: true

- name: Enable UFW
  become: true
  ansible.builtin.ufw:
    state: reloaded
    policy: deny
  when: ansible_distribution == 'Ubuntu'
