---
- name: Create build directory
  become: true
  ansible.builtin.file:
    path: /build_srcds
    state: directory
    mode: "0777"

- name: Build sourcemod
  ansible.builtin.include_role:
    name: sourcemod

- name: Copy build sources
  ansible.builtin.synchronize:
    src: ./
    dest: /build_srcds/
    archive: false
    recursive: true

# - name: Log into DockerHub
#  community.docker.docker_login:
#    username: "{{ dockerhub.username }}"
#    password: "{{ dockerhub.password }}"

- name: Build ghcr.io/leighmacdonald/uncletopia image
  community.docker.docker_image:
    name: ghcr.io/leighmacdonald/uncletopia
    tag: latest
    source: build
    force_tag: true
    push: false
    force_source: true
    build:
      nocache: false
      pull: false
      rm: false
      dockerfile: /build_srcds/Dockerfile
      path: /build_srcds/
    state: present
