---

- name: build output
  become: true
  ansible.builtin.file:
    path: /build/{{ item.server_name_short }}
    state: directory
    owner: tf2server
    mode: 0777
  loop: "{{ services }}"

- name: Generate srcdsup.yml
  become: true
  ansible.builtin.template:
    src: srcdsup.yml.j2
    dest: /build/{{ item.server_name_short }}/srcdsup.yml
    mode: 0777
  loop: "{{ services }}"
  loop_control:
    index_var: loop0

- name: srcdsup container
  docker_container:
    name: srcdsup-{{ item.server_name_short }}
    image: ghcr.io/leighmacdonald/srcdsup:master
    state: started
    restart: true
    pull: true
    interactive: true
    tty: true
    recreate: true
    restart_policy: always
    volumes:
      - ~/stv/srcds-{{ item.server_name_short }}/:/app/demos
      - srcds-{{ item.server_name_short }}-logs:/app/logs
      - /build/{{ item.server_name_short }}/srcdsup.yml:/app/srcdsup.yml
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
  loop: "{{ services }}"
  loop_control:
    index_var: loop0

