---

- name: bd-api-service
  docker_container:
    name: bd-api-service
    image: ghcr.io/leighmacdonald/bd-api:master
    restart: true
    recreate: true
    pull: true
    restart_policy: always
    state: started
    env:
      STEAM_API_KEY: "{{ steam_key }}"
    ports:
      - 127.0.0.1:8888:8888
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

- name: Join caddy network [bd-api]
  community.docker.docker_network:
    name: caddy_net
    connected:
      - bd-api-service
    appends: true

- name: Reload networks [bd-api]
  docker_container:
    name: bd-api-service
    restart: true
