- name: Create gbans_minio_data volume
  docker_volume:
    name: gbans_minio_data
    state: present

- name: Create gbans_minio_data container
  docker_container:
    name: gbans-minio
    image: minio/minio
    restart: true
    pull: true
    comparisons:
      networks: strict
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: caddy_net
    command: server /data --console-address ":9901" --address ":9900"
    env:
      MINIO_ROOT_USER: "{{ gbans_web.s3.access_key }}"
      MINIO_ROOT_PASSWORD: "{{ gbans_web.s3.secret_key }}"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    volumes:
      - gbans_minio_data:/data
    ports:
      - 127.0.0.1:9900:9900
      - 127.0.0.1:9901:9901
