---
- name: Create gbans_postgres_data volume
  docker_volume:
    name: gbans_db
    state: present

- name: Create gbans-postgres container
  docker_container:
    name: gbans-postgres
    image: postgis/postgis:13-3.2
    restart: true
    recreate: true
    pull: true
    purge_networks: true
    networks:
      - name: caddy_net
    volumes:
      - gbans_db:/var/lib/postgresql/data
    env:
      POSTGRES_DB: gbans
      POSTGRES_PASSWORD: gbans
      POSTGRES_USER: gbans
    ports:
      - 127.0.0.1:5432:5432
    command: [
      "postgres",
      "-c", "max_connections=100",
      "-c", "shared_buffers=8GB",
      "-c", "effective_cache_size=24GB",
      "-c", "maintenance_work_mem=2GB",
      "-c", "checkpoint_completion_target=0.9",
      "-c", "wal_buffers=16MB",
      "-c", "default_statistics_target=100",
      "-c", "random_page_cost=1.1",
      "-c", "effective_io_concurrency=200",
      "-c", "work_mem=10485kB",
      "-c", "min_wal_size=1GB",
      "-c", "max_wal_size=4GB",
      "-c", "max_worker_processes=8",
      "-c", "max_parallel_workers_per_gather=4",
      "-c", "max_parallel_workers=8",
      "-c", "max_parallel_maintenance_workers=4"
    ]

- name: Create gbans-postgres_exporter container
  docker_container:
    name: gbans-postgres_exporter
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    restart: true
    recreate: true
    purge_networks: true
    networks:
      - name: caddy_net
    pull: true
    env:
      DATA_SOURCE_NAME: postgresql://gbans:gbans@gbans-postgres/gbans?sslmode=disable
    ports:
      - 127.0.0.1:9187:9187
