---
# - name: create stv upload dirs
#   file:
#     path: ~/stv_demos
#     state: directory
#     owner: tf2server
#     mode: 0777
#   loop: "{{ services }}"

- name: Generate ssh private key
  ansible.builtin.template:
    src: private_key.j2
    dest: ~/.ssh/id_rsa_stv
    mode: 0600

- name: srcdsup container
  docker_container:
    name: srcdsup-{{ item.server_name_short }}
    image: leighmacdonald/srcdsup:master
    state: started
    restart: true
    pull: true
    interactive: true
    tty: true
    recreate: true
    restart_policy: always
    volumes:
      - /home/tf2server/.ssh/id_rsa_stv:/app/id_rsa.key
      - /demos/{{ item.server_name_short }}:/demos
      - /build/{{ item.server_name_short }}/srcdsup.yml:/app/srcdsup.yml
  loop: "{{ services }}"
  loop_control:
    index_var: loop0
