- name: debug
  ansible.builtin.debug:
    msg: "{{ hostvars[item]['services'] }}"
  loop: "{{ groups['all'] }}"


- name: docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: ~/docker-compose.yml
    mode: '775'

- name: Stop docker-compose
  docker_compose:
    project_src: .
    stopped: yes

- name: Start docker-compose
  docker_compose:
    project_src: .
    pull: yes
    state: present
