---

- name: Create caddy_net network
  community.docker.docker_network:
    name: caddy_net
  tags:
    - cadvisor

- name: Create cadvisor container
  docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    restart: true
    recreate: true
    restart_policy: unless-stopped
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    command:
      - '--listen_ip="0.0.0.0"'
      - '--docker_only=true'
      - '--housekeeping_interval=30s'
      - '--disable_metrics=disk,diskIO,hugetlb,referenced_memory,resctrl'
    pull: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    expose:
      - 8080
    networks:
      - name: caddy_net
    ports:
      - "{{ vpn_hosts[inventory_hostname].ip }}:8084:8080"
  tags:
    - cadvisor
