---
- name: Generate /etc/grafana.ini
  become: true
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana.ini
    mode: 0770

- name: Create grafana_data volume
  docker_volume:
    name: grafana_data
    state: present

- name: Create grafana container
  docker_container:
    name: grafana
    image: grafana/grafana-oss:latest-ubuntu
    restart: true
    recreate: true
    restart_policy: unless-stopped
    purge_networks: true
    networks:
      - name: caddy_net
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    pull: true
    volumes:
      - /etc/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    ports:
      - 127.0.0.1:3000:3000

- name: Create grafana_image_renderer container
  docker_container:
    name: grafana_image_renderer
    image: grafana/grafana-image-renderer:latest
    restart: true
    recreate: true
    restart_policy: unless-stopped
    networks:
      - name: caddy_net
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    pull: true
    ports:
      - 127.0.0.1:8081:8081
