---

#- name: Enable rsyslog
#  ansible.builtin.include_role:
#    name: hadret.rsyslog

- name: Generate /etc/promtail.yml
  become: true
  ansible.builtin.template:
    src: promtail.yml.j2
    dest: /etc/promtail.yml
    mode: 0770

- name: Create promtail container
  docker_container:
    name: promtail
    image: grafana/promtail:latest
    restart: true
    pull: true
    purge_networks: true
    restart_policy: unless-stopped
    recreate: true
    command: ["-config.file=/etc/promtail.yml"]
    networks:
      - name: caddy_net
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    volumes:
      - /etc/promtail.yml:/etc/promtail.yml
      - /etc/machine-id:/etc/machine-id
      - /var/log/journal/:/var/log/journal/
      - /run/log/journal/:/run/log/journal/
      - /var/run/docker.sock:/var/run/docker.sock
      - tempo_data:/tmp/tempo
    ports:
      - "{{ vpn_hosts[metrics_hostname].ip }}:9080:9080"
